spring.application.name=pelisbdapi
spring.datasource.url=jdbc:postgresql://localhost:5432/pelisbd
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=86400000
server.port=3000
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_HOST}
tmdb.api.key=${TMDB_API_KEY}
spring.config.import=optional:file:.env.local[.properties]
app.frontend.url = ${FRONTEND_URL}
app.frontend.ip = ${FRONTEND_IP}
api.key=${API_KEY}
