spring.application.name=pelisbdapi
spring.datasource.url=jdbc:postgresql://localhost:5432/pelisbd
spring.datasource.username=admindevartur
spring.datasource.password=A82zvm-123Y8
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.jwt.secret=T+m/GEzXE+3daCzSN4ENp39wC5rO3YChFXoCdUvuCrXoMWSprmODy/sfcw07s3G6h3OAuQ/lcNxN0CCy06yQ5Q==
app.jwt.expiration-ms=86400000
server.port=3000
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_HOST}
tmdb.api.key=${TMDB_API_KEY}
spring.config.import=optional:file:.env.local[.properties]

