services:
  dbpelis:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admindevartur
      POSTGRES_PASSWORD: A82zvm-123Y8
      POSTGRES_DB: pelisbd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./build/postgree/testdatabase.sql:/docker-entrypoint-initdb.d/testdatabase.sql:ro
    networks:
      - app-network

  backendpelis:
    build:
      context: ./src-springboot
      dockerfile: ../build/springboot/Dockerfile
    container_name: backend-pelis
    restart: always
    depends_on:
      - dbpelis
    ports:
      - "3000:3000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbpelis:5432/pelisbd
      SPRING_DATASOURCE_USERNAME: admindevartur
      SPRING_DATASOURCE_PASSWORD: A82zvm-123Y8
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network
    env_file:
      - .env.local

  webpelis:
    build:
      context: .
      dockerfile: ./build/apache/Dockerfile
    container_name: apache-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs:ro
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
